<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FM26PlayerExport</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="BepInEx.Core" />
    <Reference Include="BepInEx.Unity.IL2CPP" />
    <Reference Include="UnityEngine.CoreModule" />
    <Reference Include="System.Collections">
      <HintPath>..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.24\System.Collections.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule" />
    <Reference Include="Il2CppInterop.Runtime" />
    <Reference Include="System.Text.RegularExpressions">
      <HintPath>..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.24\System.Text.RegularExpressions.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem" />
    <Reference Include="System.Text.Encoding.Extensions">
      <HintPath>..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.24\System.Text.Encoding.Extensions.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule" />
    <Reference Include="Il2Cppmscorlib" />
  </ItemGroup>
</Project>